CREATE DATABASE QLLOGIN
GO
USE QLLOGIN

CREATE TABLE Users
(
	username VARCHAR(10) PRIMARY KEY,
	passwords VARCHAR(10),
	yourname VARCHAR(10),
	email VARCHAR(30)
)

CREATE TABLE WRITE_CONTENT
(
	WRITERS VARCHAR(10) NOT NULL,
	TITLES VARCHAR(800) NOT NULL,
	HASHTAGS VARCHAR(3000) NOT NULL,
	CONTENTS VARCHAR(5000) NOT NULL,
)

CREATE TABLE FOLLOW
(
	FOLLOWER VARCHAR(10) NOT NULL,
	BE_FOLLOWED VARCHAR(10) NOT NULL
)

CREATE TABLE COMMENT
(
	WRITERS VARCHAR(10) NOT NULL,
	TITLES VARCHAR(800) NOT NULL,
	COMMENTS VARCHAR(3000),
	USERS VARCHAR(10) NOT NULL
)


ALTER TABLE FOLLOW ADD CONSTRAINT PK_FOLLOWER_BE_FOLLOWED PRIMARY KEY (FOLLOWER, BE_FOLLOWED)

ALTER TABLE FOLLOW ADD CONSTRAINT FK_FOLLOWER_Users FOREIGN KEY (FOLLOWER) REFERENCES Users (username)

ALTER TABLE FOLLOW ADD CONSTRAINT FK_FOLLOWED_Users FOREIGN KEY (BE_FOLLOWED) REFERENCES Users (username)

ALTER TABLE WRITE_CONTENT ADD LIKES INT DEFAULT 0 

ALTER TABLE WRITE_CONTENT ADD CONSTRAINT FK_UsersWRITE_CONTENT FOREIGN KEY (WRITERS) REFERENCES Users(username)

ALTER TABLE WRITE_CONTENT ADD CONSTRAINT PK_WRITERS_TITLES PRIMARY KEY (WRITERS, TITLES)

ALTER TABLE COMMENT ADD CONSTRAINT FK_U_Users_u FOREIGN KEY (USERS) REFERENCES Users (username)

ALTER TABLE COMMENT ADD CONSTRAINT FK_W_WRITE_CONTENT_W FOREIGN KEY (WRITERS,TITLES) REFERENCES WRITE_CONTENT (WRITERS,TITLES)

